/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check the status of all microservices. */
    get: operations['AppController_healthCheck']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['UsersController_getUsers']
    put?: never
    post: operations['UsersController_createUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['UsersController_getUserById']
    put?: never
    post?: never
    delete: operations['UsersController_deleteUser']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/registration': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User Registration. */
    post: operations['AuthController_registration']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/email-resend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Resend Confirmation email. */
    post: operations['AuthController_resendEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/confirm-email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm email to complete registration */
    post: operations['AuthController_confirmEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User login */
    post: operations['AuthController_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh-token': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh tokens. In cookie client must send refreshToken */
    post: operations['AuthController_refreshToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User Logout. */
    post: operations['AuthController_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get current user information. */
    get: operations['AuthController_getMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/password-recovery': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Password recovery via email confirmation */
    post: operations['AuthController_passwordRecovery']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/new-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Set new password */
    post: operations['AuthController_newPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/google': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Initiate Google OAuth authentication
     * @description Redirects user to Google OAuth authorization page. Frontend should redirect user to this endpoint via window.location.href or <a> tag.
     */
    get: operations['AuthController_googleAuth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/github': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Initiate GitHub OAuth authentication
     * @description Redirects user to GitHub OAuth authorization page. Frontend should redirect user to this endpoint via window.location.href or <a> tag.
     */
    get: operations['AuthController_githubAuth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/google/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Google OAuth callback handler
     * @description Internal callback endpoint. Called automatically by Google after user authorization. Do not call manually.
     */
    get: operations['AuthController_googleAuthRedirect']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/github/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * GitHub OAuth callback handler
     * @description Internal callback endpoint. Called automatically by GitHub after user authorization. Do not call manually.
     */
    get: operations['AuthController_githubAuthRedirect']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/devices': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all user devices
     * @description This endpoint retrieves all devices associated with the authenticated user.
     */
    get: operations['DeviceController_getAllUserDevices']
    put?: never
    post?: never
    /**
     * Delete other sessions
     * @description Deletes all user sessions except the current one
     */
    delete: operations['DeviceController_terminateOtherSessions']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/devices/{sessionId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete device by session ID
     * @description This endpoint allows the user to delete a specific device session by providing its session ID.
     */
    delete: operations['DeviceController_terminateSessionById']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/create-post': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create a new post
     * @description This endpoint allows you to create a new post with up to 10 images.
     */
    post: operations['PostsController_createPost']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get post by ID
     * @description Retrieves a post by its unique identifier.
     */
    get: operations['PostsController_getPostById']
    /**
     * Update post description
     * @description This endpoint allows you to update existing posts description field
     */
    put: operations['PostsController_updatePost']
    post?: never
    /**
     * Delete existing post
     * @description this endpoint deletes a post by post id.
     */
    delete: operations['PostsController_deletePostById']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get posts
     * @description This endpoint retrieves a list of posts with pagination and sorting options.
     */
    get: operations['PostsController_getPosts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/profile/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get profile info
     * @description This endpoint retrieves profile info
     */
    get: operations['ProfileController_getProfile']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update user profile
     * @description This endpoint allows you to update your profile data
     */
    patch: operations['ProfileController_updateProfile']
    trace?: never
  }
  '/profile/avatar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete user avatar
     * @description This endpoint allows you to delete avatar
     */
    delete: operations['ProfileController_deleteAvatar']
    options?: never
    head?: never
    /**
     * Upload user avatar
     * @description This endpoint allows you to upload avatar
     */
    patch: operations['ProfileController_updateAvatar']
    trace?: never
  }
  '/location/countries': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all countries
     * @description Getting all countries
     */
    get: operations['LocationController_getCountries']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/location/countries/{countryId}/cities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all Cities by country id
     * @description Getting all cities list by country id
     */
    get: operations['LocationController_getCitiesByCountryId']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/location/cities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all cities
     * @description Getting all cities from the server, for list of the cities.
     */
    get: operations['LocationController_getAllCities']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get stats
     * @description Getting stats from the server, for list of the stats.
     */
    get: operations['StatsController_getStats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    MainServiceInfo: {
      status: string
      timestamp: string
    }
    FilesServiceInfo: {
      status: string
      timestamp: string
    }
    NotificationServiceInfo: {
      status: string
      timestamp: string
    }
    HealthViewDto: {
      mainService: components['schemas']['MainServiceInfo']
      filesService: components['schemas']['FilesServiceInfo']
      notificationService: components['schemas']['NotificationServiceInfo']
    }
    UserInputDto: {
      username: string
      /** @example user@email.com */
      email: string
      password: string
      /** @description Must match with password */
      passwordConfirmation: string
      /** @description Agree to terms. Must be true. */
      agreeToTerms: boolean
    }
    ErrorMessageDto: {
      message: string
      field?: string
    }
    ErrorResponseDto: {
      errorsMessages: components['schemas']['ErrorMessageDto'][]
    }
    EmailResendInputDto: {
      email: string
    }
    ConfirmCodeInputDto: {
      code: string
    }
    ErrorMessageBaseDto: {
      message: string
    }
    WithoutFieldErrorResponseDto: {
      errorsMessages: components['schemas']['ErrorMessageBaseDto'][]
    }
    LoginInputDto: {
      /**
       * @description Email address. You can enter registered email.
       * @example user@example.com
       */
      email: string
      password: string
    }
    LoginViewDto: {
      accessToken: string
    }
    AuthMeViewDto: {
      id: string
      username: string
      email: string
      isConfirmed: boolean
    }
    PasswordRecoveryInputDto: {
      /**
       * @description Email address of the user requesting password recovery
       * @example example@gmail.com
       */
      email: string
      /**
       * @description Captcha token to verify the request
       * @example captcha-token-12345
       */
      captchaToken: string
    }
    NewPasswordInputDto: {
      /**
       * @description New password for the user. Must be 6-20 characters long, include at least one uppercase letter, one lowercase letter, one digit, and one special character.
       * @example NewPassword123!
       */
      newPassword: string
      /**
       * @description Recovery code for password reset. Sent to the user's email and required to set a new password.
       * @example d67d5893-ab05-4c1e-b866-f4c8494ca03f
       */
      recoveryCode: string
    }
    TokenResponseDto: Record<string, never>
    DeviceViewDto: {
      /**
       * @description Unique identifier of the device.
       * @example d67d5893-ab05-4c1e-b866-f4c8494ca03f
       */
      deviceId: number
      /**
       * @description user id of the user associated with the device.
       * @example Ivan
       */
      userId: Record<string, never> | null
      /**
       * @description Type of the device (e.g., "Chrome").
       * @example Chrome
       */
      deviceName: Record<string, never> | null
      /**
       * @description IP address of the device.
       * @example 192.168.1.1
       */
      ip: Record<string, never> | null
      /**
       * @description Session ID associated with the device.
       * @example d67d5893-ab05-4c1e-b866-f4c8494ca03f
       */
      sessionId: string
      /**
       * @description Date and time when the device was last updated.
       * @example 2023-10-02T12:00:00Z
       */
      updatedAt: Record<string, never> | null
    }
    CreatePostInputDto: {
      /**
       * @description description
       * @example short description of post
       */
      description: string
      /** @description Post images (max 10) */
      files: string[]
    }
    UpdatePostInputDto: {
      /**
       * @description description
       * @example new post description
       */
      description: string
    }
    PostUserDto: {
      /**
       * @description Unique identifier of the user.
       * @example 15
       */
      userId: number
      /**
       * @description Username of the user.
       * @example test user
       */
      username: string
    }
    PostViewDto: {
      /**
       * @description Unique identifier of the post.
       * @example 1
       */
      id: number
      /** @description User who created the post. */
      user: components['schemas']['PostUserDto']
      /**
       * @description Content of the post.
       * @example This post explains how to use decorators in TypeScript...
       */
      description: string
      /**
       * @description Preview images of the post.
       * @example [
       *       "https://example.com/image1.jpg",
       *       "https://example.com/image2.jpg"
       *     ]
       */
      previewImages: string[]
      /**
       * Format: date-time
       * @description Date when the post was created.
       * @example 2023-10-01T12:00:00Z
       */
      createdAt: string
    }
    PagedPostViewDto: {
      /** @description Array of Posts */
      items: components['schemas']['PostViewDto'][]
      totalCount: number
      pagesCount: number
      page: number
      pageSize: number
    }
    ProfileViewDto: {
      /**
       * @description User id
       * @default 1
       */
      userId: number
      /** @default username */
      username: string
      /** @default John */
      firstname: Record<string, never>
      /** @default Doe */
      lastname: Record<string, never>
      /** @default New York */
      city: Record<string, never> | null
      /** @default USA */
      country: Record<string, never> | null
      /** @default Something about me */
      aboutMe: Record<string, never> | null
      /** @default https://s3-storage.com/bucket/somefile */
      avatarUrl: Record<string, never> | null
    }
    ProfileInputDto: {
      /**
       * @description First name of the user
       * @example John
       */
      firstName?: string
      /**
       * @description Last name of the user
       * @example Doe
       */
      lastName?: string
      /**
       * @description Date of birth in format dd.mm.yyyy
       * @example 15.05.2000
       */
      dateOfBirth?: string
      /**
       * @description Country ID from list
       * @example 2
       */
      countryId?: number
      /**
       * @description City ID from list
       * @example 1
       */
      cityId?: number
      /**
       * @description About me section (max 200 characters)
       * @example Software developer passionate about clean code and architecture
       */
      aboutMe?: string
    }
    UploadAvatarDto: {
      /**
       * Format: binary
       * @description Image (max 1)
       */
      avatar: string
    }

    CountryViewDto: {
      /**
       * @description Country id
       * @example 1
       */
      id: number
      /**
       * @description Country name
       * @example Japan
       */
      name: string
      /**
       * @description Country code
       * @example JP
       */
      code: string
    }
    CityViewDto: {
      /**
       * @description City id
       * @example 1
       */
      id: number
      /**
       * @description City name
       * @example Tokyo
       */
      name: string
      /**
       * @description Country id
       * @example 1
       */
      countryId: number
    }
    OutputStatsViewDto: {
      /**
       * @description Total posts count
       * @example 100
       */
      totalPostsCount: number
      /**
       * @description Total users count
       * @example 100
       */
      totalUsersCount: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  AppController_healthCheck: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthViewDto']
        }
      }
    }
  }
  UsersController_getUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserInputDto']
      }
    }
    responses: {
      /** @description Returns the newly created user */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description If the inputModel has incorrect values */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_getUserById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_deleteUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Success */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_registration: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description User credentials and email */
    requestBody: {
      content: {
        'application/json': components['schemas']['UserInputDto']
      }
    }
    responses: {
      /** @description Registration successful, no content returned */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid input or username/email already taken */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description More than 2 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_resendEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Email */
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailResendInputDto']
      }
    }
    responses: {
      /** @description Email resend successful, no content returned */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Email input has incorrect values or email already confirmed */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_confirmEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Confirmation code */
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmCodeInputDto']
      }
    }
    responses: {
      /** @description Email successfully confirmed. No content returned. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Email is already confirmed or confirmation code has expired. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description User with this confirmation code was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Username or email and password */
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginInputDto']
      }
    }
    responses: {
      /** @description Login successful. The access token is returned in the response body, while the refresh token is set in the HttpOnly cookie. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginViewDto']
        }
      }
      /** @description Login failed. Invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_refreshToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The access token is returned in the response body, while the refresh token is set in the HttpOnly cookie */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginViewDto']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logout successful, no content returned */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Logout failed. Bad request, possibly due to invalid input. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Logout failed. User is not authenticated. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns the current user information. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthMeViewDto']
        }
      }
      /** @description User is not authenticated. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_passwordRecovery: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordRecoveryInputDto']
      }
    }
    responses: {
      /** @description Password recovery email sent successfully. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid email address */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_newPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NewPasswordInputDto']
      }
    }
    responses: {
      /** @description New password set successfully. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request contains invalid data, or the password recovery code is invalid or has expired. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found or password recovery code does not match. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description More than 5 attempts from one IP-address during 10 seconds */
      429: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_googleAuth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successfully redirects to Google OAuth authorization page */
      307: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid OAuth parameters or missing configuration */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  AuthController_githubAuth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successfully redirects to GitHub OAuth authorization page */
      307: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid OAuth parameters or missing configuration */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  AuthController_googleAuthRedirect: {
    parameters: {
      query: {
        /** @description Authorization code from Google */
        code: string
        /** @description State parameter for security */
        state?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Authentication successful, returns tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponseDto']
        }
      }
      /** @description Invalid authorization code from Google or OAuth parameters error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description Google OAuth authentication failed or invalid Google user data */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description User not found during login process */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  AuthController_githubAuthRedirect: {
    parameters: {
      query: {
        /** @description Authorization code from GitHub */
        code: string
        /** @description State parameter for security */
        state?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Authentication successful, returns tokens */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponseDto']
        }
      }
      /** @description Invalid authorization code from GitHub or OAuth parameters error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description GitHub OAuth authentication failed or invalid GitHub user data */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description User not found during login process */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  DeviceController_getAllUserDevices: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successfully retrieved all user devices. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeviceViewDto']
        }
      }
      /** @description User is not authenticated or token is invalid. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  DeviceController_terminateOtherSessions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Sessions deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Refresh token is invalid or has expired. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No other sessions found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  DeviceController_terminateSessionById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the device session to delete */
        sessionId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Device session deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User is not authenticated or token is invalid. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Device session not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  PostsController_createPost: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Post data with images */
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['CreatePostInputDto']
      }
    }
    responses: {
      /** @description Post successfully created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User is not authenticated or token is invalid. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
    }
  }
  PostsController_getPostById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Post ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Post retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostViewDto']
        }
      }
      /** @description Invalid post ID. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Post not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  PostsController_updatePost: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Post id (integer) */
        id: number
      }
      cookie?: never
    }
    /** @description new description */
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePostInputDto']
      }
    }
    responses: {
      /** @description Description successfully updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Description is invalid or empty */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description User is not authenticated or token expired */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description User is not the owner of resource */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  PostsController_deletePostById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Post id (integer) */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Post successfully deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User is not authenticated or token expired */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description User is not the owner of resource */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  PostsController_getPosts: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        pageNumber?: number
        /** @description Number of items per page */
        pageSize?: number
        /** @description Field to sort by */
        sortBy?: string
        /** @description Sort direction (ASC or DESC) */
        sortDirection?: 'ASC' | 'DESC'
        /** @description User ID */
        userId?: number
        /** @description description */
        description?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Posts retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PagedPostViewDto']
        }
      }
      /** @description Invalid query parameters provided. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No posts found for the given criteria. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ProfileController_getProfile: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User Id */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProfileViewDto']
        }
      }
      /** @description User id is invalid */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  ProfileController_updateProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Profile data to update */
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileInputDto']
      }
    }
    responses: {
      /** @description Profile updated successfully with no content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponseDto']
        }
      }
      /** @description User is not authenticated or token expired */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  ProfileController_deleteAvatar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Delete successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
      /** @description Profile not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  ProfileController_updateAvatar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Upload user avatar */
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['UploadAvatarDto']
      }
    }
    responses: {
      /** @description Upload successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LocationController_getCountries: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CountryViewDto'][]
        }
      }
      /** @description Countries not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  LocationController_getCitiesByCountryId: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description country ID */
        countryId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CityViewDto'][]
        }
      }
      /** @description Cities not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  LocationController_getAllCities: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CityViewDto'][]
        }
      }
      /** @description Cities not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WithoutFieldErrorResponseDto']
        }
      }
    }
  }
  StatsController_getStats: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Getting stats from the server, for list of the stats. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OutputStatsViewDto']
        }
      }
    }
  }
}
