import type { Metadata } from "next";
import { ReactNode } from "react";
import "@irondragons/ui-lib-inctagram/dist/style.css";
import s from "./page.module.scss";

export const metadata: Metadata = {
  title: "Inctagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={s.rootLayout}>{children}</div>
      </body>
    </html>
  );
}
