import createClient from "openapi-fetch";
import type { paths, components } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_BASE_URL,
  credentials: "include",
});
