import createClient from "openapi-fetch";
import type { paths, components } from "./schema"; // generated by openapi-typescript

// TODO: вынести отдельно
export const TokenService = {
  setToken(token: string) {
    localStorage.setItem("accessToken", token);
  },
  getToken() {
    return localStorage.getItem("accessToken");
  },
  clear() {
    localStorage.removeItem("accessToken");
  },
};

export const client = createClient<paths>({
  baseUrl: "https://nodewebdev.online/api/v1/",
  headers: {
    Authorization: `Bearer ${TokenService.getToken()}`, // Пример авторизации
  },
  credentials: "include",
});
